### ISSUE TITLE
`np.ones_like` doesn't work on data pointers

### ISSUE THREAD

**Issue by kiendang** [OpenMined/PySyft#7041] opened 2022-11-14 05:18 UTC
## Description
`np.ones_like(d_ptr)` throws `ValueError: Invalid Numpy Operation: ones_like for DSA`.

## How to Reproduce

```py
import syft as sy
import numpy as np

domain_client = sy.login(email="info@openmined.org", password="changethis", port=8081)

arr = np.random.randint(0, 10000, (10000))

data = sy.Tensor(arr).annotate_with_dp_metadata(-1, 11000, data_subjects="Bob")
data_ptr = data.send(domain_client, tags=["my_data"])

domain_client.create_user(name="DS", email="test@email.com", password="password", budget=99999)
ds_client = sy.login(email="test@email.com", password="password", port=8081)

d_ptr = ds_client.store[data_ptr.id_at_location]

np.ones_like(d_ptr)
```

```py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [7], line 1
----> 1 np.ones_like(d_ptr)

File <__array_function__ internals>:180, in ones_like(*args, **kwargs)

File ~/pysyft/packages/syft/src/syft/core/tensor/passthrough.py:698, in PassthroughTensor.__array_function__(self, func, types, args, kwargs)
    696 implementation = query_implementation(self.__class__, func)
    697 if implementation:
--> 698     return implementation(*args, **kwargs)
    699 return self.__class__(func(*args, **kwargs))

File ~/pysyft/packages/syft/src/syft/core/tensor/autodp/phi_tensor.py:1693, in ones_like(tensor, *args, **kwargs)
   1687 @implements(TensorWrappedPhiTensorPointer, np.ones_like)
   1688 def ones_like(
   1689     tensor: TensorWrappedPhiTensorPointer,
   1690     *args: Any,
   1691     **kwargs: Any,
   1692 ) -> TensorWrappedPhiTensorPointer:
-> 1693     return tensor.ones_like(*args, **kwargs)

File ~/pysyft/packages/syft/src/syft/core/tensor/autodp/phi_tensor.py:962, in TensorWrappedPhiTensorPointer.ones_like(self, *args, **kwargs)
    949 def ones_like(
    950     self,
    951     *args: Any,
    952     **kwargs: Any,
    953 ) -> TensorWrappedPhiTensorPointer:
    954     """Apply the "ones_like" operation between "self" and "other"
    955 
    956     Args:
   (...)
    960         Union[TensorWrappedPhiTensorPointer,MPCTensor] : Result of the operation.
    961     """
--> 962     return self._apply_self_tensor_op("ones_like", *args, **kwargs)

File ~/pysyft/packages/syft/src/syft/core/tensor/autodp/phi_tensor.py:318, in TensorWrappedPhiTensorPointer._apply_self_tensor_op(self, op_str, *args, **kwargs)
    316         data_subjects = self.data_subjects
    317 else:
--> 318     raise ValueError(f"Invalid Numpy Operation: {op_str} for DSA")
    320 result = TensorWrappedPhiTensorPointer(
    321     data_subjects=data_subjects,
    322     min_vals=min_vals,
    323     max_vals=max_vals,
    324     client=self.client,
    325 )
    327 # QUESTION can the id_at_location be None?

ValueError: Invalid Numpy Operation: ones_like for DSA
```

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by iamtrask** [comment] 2022-11-17 11:50
Before fixing this we need to decide whether we're actually going to try to modify the numpy API or whether we should just make an imitation syft.numpy module where we define our own methods (like zeroes_like()) with no connection to actual numpy. If unsure we should do the latter for now because it's easier to build and easier to change later (and less likely to be buggy)

**Comment by madhavajay** [comment] 2022-11-18 06:43
@kiendang is this a duplicate of this issue: https://github.com/OpenMined/PySyft/issues/6922

**Comment by kiendang** [comment] 2022-11-18 10:57
I don't think so. `ones_like` was implemented but doesn't work. Maybe @rasswanth-s can confirm?

**Comment by madhavajay** [comment] 2022-11-21 03:02
Sorry I mean the `ufunc` support:
https://github.com/OpenMined/PySyft/issues/7042

**Comment by kiendang** [comment] 2022-11-21 05:09
Could be related. What I understand is `ufunc` support for `np.ones_like` was supposed to work but broken? #7042 is discussing whether we support `ufunc` at all? So yes, these 2 issues are closely related.

**Closed** 2022-11-24 14:48 UTC
Labels: Type: Bug :bug:, Priority: 1 - Immediate :fire:, 0.7, Syft, Awaiting Response
