### ISSUE TITLE
Importing Syft causes errors in the logs

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6951] opened 2022-11-03 14:30 UTC
Co-authored by @teo-milea

Just importing Syft (the first cell in the notebook) raises errors in the backend container: 

![Image](https://user-images.githubusercontent.com/32711264/199748592-8483a16f-6fdc-4644-b5dc-8d4c6fce5f08.png)

**Comment by madhavajay** [comment] 2022-11-08 01:45
Duplicate of GarbageCollectionAction error.

**Closed by madhavajay** 2022-11-08 01:45 UTC
