### ISSUE TITLE
Quickstart Syft Client Installation Failing

### ISSUE THREAD

**Issue by H4LL** [OpenMined/PySyft#8532] opened 2024-02-27 14:00 UTC
## Description
Following the instructions on the README.md for quickstart installation of the syft client I tried this line:
`pip install -U syft[data_science]`

Received:
`zsh: no matches found: syft[data_science]`

## How to Reproduce
1. Start a terminal
2. Create new conda env: `conda create --name syft_test python=3.8`
3. Activate env: `conda activate syft_test`
4. Run  `pip install -U syft[data_science]`
5. See error:
`zsh: no matches found: syft[data_science]`

## Expected Behavior
This should install the syft client.

## Screenshots
<img width="548" alt="Screenshot 2024-02-27 at 1 59 10 PM" src="https://github.com/OpenMined/PySyft/assets/46713492/f406a44e-f770-4673-99b5-4138c75d0eb2">

## System Information
 - OS: Mac OS
 - OS Version: Sonoma 14.1.1 (23B2082)
 - Language Version: Python 3.8
 - Package Manager Version: conda 23.7.4
 - Browser (if applicable): N/A
 - Browser Version (if applicable): N/A

## Additional Context
Running pip install syft runs fine. It seems to be an issue with this method of installing the syft client.

**Comment by H4LL** [comment] 2024-02-27 14:39
I also tested this after upgrading python to 3.11.8:
<img width="586" alt="Screenshot 2024-02-27 at 2 38 38 PM" src="https://github.com/OpenMined/PySyft/assets/46713492/b4be156a-af43-485d-a978-82af9a9f817a">

**Comment by madhavajay** [comment] 2024-03-04 03:17
Hi @H4LL, I think the issue is `zsh`. I use it as well but the syntax for `[` extras requires `"` quotes.

```
$ pip install -U "syft[data_science]"
```

**Comment by madhavajay** [comment] 2024-03-07 08:20
@H4LL Adam did you get this to work? I will close this for now as I know that its related to quotes on my zsh.

**Closed as completed by madhavajay** 2024-03-07 08:20 UTC
Labels: Type: Bug :bug:, Awaiting Response
