### ISSUE TITLE
Documentation - Beat the Sphinx

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1539] opened 2018-09-21 13:13 UTC
We have Sphinx for building documentation but we have trouble to configurate it.

Main issues are:
- Having a left panel which show all the major module and classes
- Having Sphinx displaying doc for classes and functions starting with "_"

Can you beat the sphinx ?

**Comment by jeremyjordan** [comment] 2018-09-21 22:46
Hmm that's odd, I'll pull down the repo in a few hours and see if I can figure it out. I recently had to set up a Sphinx documentation site for work so this is fresh on my mind - hopefully it's a quick fix.

**Comment by jeremyjordan** [comment] 2018-09-22 01:06
Ok, I believe the problem is the documentation has multiple redundancies of `autodoc`'d modules  (so when you use `:private-members:` it's being overwritten somewhere else); I'm not sure how you want to organize the docs but the current organization is a bit unwieldy at first glance.

Also, if you want to show *all* methods (including magic methods) you'll also want to include `:special-members:`.

**Comment by jeremyjordan** [comment] 2018-09-23 23:39
@LaRiffle See if you can pull down the branch in [this PR](https://github.com/OpenMined/PySyft/pull/1553) and see if this solution serves your needs.

**Comment by jeremyjordan** [comment] 2018-09-24 01:02
![screen shot 2018-09-23 at 9 02 04 pm](https://user-images.githubusercontent.com/13970565/45934991-feb1a780-bf73-11e8-96fa-adc7a4ca7ffd.png)

**Comment by iamtrask** [comment] 2018-09-24 12:19
Absolutely killer job!!! Merged!!! Thank you so much Jeremy!!

**Closed by iamtrask** 2018-09-24 12:19 UTC
Labels: good first issue
