### ISSUE TITLE
Error with PySyft federated learning remote worker 

### ISSUE THREAD

**Issue by wmlba** [OpenMined/PySyft#3245] opened 2020-03-23 11:26 UTC
**Describe the bug**
TrainConfig.send() to a remote client throw an error

**To Reproduce**
1- Create a remote client on a different server.
2- Run the code in Introduction To TrainConfig notebook.
3- replace localhost with the IP of the remote server that has the worker running
4- train_config.send(alice) will throw an error

**Error Message **
This is the error message from the worker side:

`worker <WebsocketServerWorker id:alice #objects:0> received WorkerCommandMessage ('_log_msgs', ((), {'value': False}, []))
Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=AttributeError("'ObjectMessage' object has no attribute 'contents'")>
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 317, in recv_msg
    print(f"worker {self} received {type(msg).__name__} {msg.contents}")
AttributeError: 'ObjectMessage' object has no attribute 'contents'
Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_server.py:95> exception=AttributeError("'ObjectMessage' object has no attribute 'contents'")>
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File "/home/ec2-user/miniconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 317, in recv_msg
    print(f"worker {self} received {type(msg).__name__} {msg.contents}")
AttributeError: 'ObjectMessage' object has no attribute 'contents'`

**Screenshots**
Notebook Screenshot:
![Screen Shot 2020-03-24 at 12 21 16 AM](https://user-images.githubusercontent.com/18373707/77311739-8fce2e00-6d65-11ea-9e17-144749eea3df.png)

**Desktop (please complete the following information):**
 - OS: Amazon Linux x86_64
 - Python 3.7
- PySyft 0.2.4

**Comment by gconst02** [comment] 2020-03-27 18:29
You probably run it with `--verbose` arg which causes the `msg.contents` print. Try running the remote worker without the param, as a temporary fix.

**Comment by karlhigley** [comment] 2020-03-27 18:54
I think the underlying issue is [in `BaseWorker`](https://github.com/OpenMined/PySyft/blob/master/syft/workers/base.py#L316-L317). The problem is that the base `Message` class no longer has a `contents` property, so none of the sub-classes do either.

**Comment by jmaunon** [comment] 2020-05-05 06:21
I think this issue is already fixed in the following commit:
https://github.com/OpenMined/PySyft/commit/e4b5cab232910968036f8bac1d499b19356de41c

@karlhigley If you agree this issue could be closed

**Closed** 2020-05-05 18:44 UTC
Labels: bug
