### ISSUE TITLE
Suspicious behavior: mean() query DP logic misbehaving - also changing the order of queries radically changes privacy budget spend

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6917] opened 2022-10-28 23:54 UTC
First I launched a fresh node (hagrid launch --tag=latest) and ran the following code:

```
import syft as sy

me = sy.login(email="info@openmined.org", password="changethis", port=8081)

import numpy as np

n = 1000
_x = (np.random.randn(n) * 100)
a = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x)+":A", range(0,n))))

n = 10000
_x = (np.random.randn(n) * 100)
b = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x)+":B", range(0,n))))

me.load_dataset(assets={"a":a, "b":b}, 
                name="Test Dataset", 
                description="Short Desc")


me.create_user(name='Bob',
               email="andrew2@openmined.org",
               password="abc123",
               budget=10000000)

bob = sy.login(email="andrew2@openmined.org",
               password="abc123",
               port=8081)

initial_budget = bob.privacy_budget

x = bob.datasets[-1]['a']

out_ptr = x.mean().publish(sigma=1)
out = out_ptr.block.get()

final_budget = bob.privacy_budget

print(initial_budget, final_budget, out)


initial_budget = bob.privacy_budget

x = bob.datasets[-1]['b']

out_ptr = x.mean().publish(sigma=1)
out = out_ptr.block.get()

final_budget = bob.privacy_budget

print(initial_budget, final_budget, out)
```

which returned the following output

```
WARNING: CHANGE YOUR USERNAME AND PASSWORD!!! 

Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to localhost... done! 	 Logging into upbeat_bostrom... done!
Tensor annotated with DP Metadata
Tensor annotated with DP Metadata
Loading dataset... uploading...🚀                                                                                                                                             
Uploading `a`: 100%|██████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.62it/s]
Uploading `b`: 100%|██████████████████████████████████████████████████| 1/1 [00:00<00:00, 85.03it/s]
Dataset is uploaded successfully !!! 🎉

Run `<your client variable>.datasets` to see your new dataset loaded into your machine!
User created successfully!
Connecting to localhost... done! 	 Logging into upbeat_bostrom... done!
/Users/atrask/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:179: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
10000000.0 9302008.281889187 0.33724222362735695
9302008.281889187 8605446.929564001 2.11641244432264
```

This was concerning because running a mean() query on 10x more data subjects should spend 1/10th the amount of privacy budget, but it spent almost the same amount. Very strange. 

But things got stranger in a different way when I reversed the order of quering against datasets "a" and "b".

I launched a new node with "hagrid launch --tag=latest" and  ran the following code

```
import syft as sy

me = sy.login(email="info@openmined.org", password="changethis", port=8081)

import numpy as np

n = 1000
_x = (np.random.randn(n) * 100)
a = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x)+":A", range(0,n))))

n = 10000
_x = (np.random.randn(n) * 100)
b = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x)+":B", range(0,n))))

me.load_dataset(assets={"a":a, "b":b}, 
                name="Test Dataset", 
                description="Short Desc")


me.create_user(name='Bob',
               email="andrew2@openmined.org",
               password="abc123",
               budget=10000000)

bob = sy.login(email="andrew2@openmined.org",
               password="abc123",
               port=8081)

initial_budget = bob.privacy_budget

x = bob.datasets[-1]['a']

out_ptr = x.mean().publish(sigma=1)
out = out_ptr.block.get()

final_budget = bob.privacy_budget

print(initial_budget, final_budget, out)


initial_budget = bob.privacy_budget

x = bob.datasets[-1]['b']

out_ptr = x.mean().publish(sigma=1)
out = out_ptr.block.get()

final_budget = bob.privacy_budget

print(initial_budget, final_budget, out)
```

This gave me the following output:

```
WARNING: CHANGE YOUR USERNAME AND PASSWORD!!! 

Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to localhost... done! 	 Logging into intelligent_ng... done!
Tensor annotated with DP Metadata
Tensor annotated with DP Metadata
Loading dataset... uploading...🚀                                                                                                                                             
Uploading `a`: 100%|██████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.62it/s]
Uploading `b`: 100%|██████████████████████████████████████████████████| 1/1 [00:00<00:00, 85.03it/s]
Dataset is uploaded successfully !!! 🎉

Run `<your client variable>.datasets` to see your new dataset loaded into your machine!
User created successfully!
Connecting to localhost... done! 	 Logging into intelligent_ng... done!
/Users/atrask/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:179: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
10000000.0 9303768.11488111 0.33724222362735695
9303768.11488111 9303756.508847252 2.11641244432264
```

This time the privacy budget spend for the second query was almost NOTHING. I don't know have a good explanation for why, but it seems related to: https://github.com/OpenMined/PySyft/issues/6916

**Comment by iamtrask** [comment] 2022-11-20 00:47
The quick fix here is to delete the mean() code that is DP specific (and likely incorrect) and add a mean() op to the PassthroughTensor which calls (roughly) self.sum(dim) / self.public_shape[dim]. As an added bonus, we'll get mean() for SMPC too.

**Comment by IshanMi** [comment] 2022-11-22 15:24
Launching a domain node using `hagrid launch --tag=latest` launched a domain node with Syft 0.6.0- could this be the cause of the issue?

**Comment by IshanMi** [comment] 2022-11-22 20:14
![image](https://user-images.githubusercontent.com/32711264/203412188-a47c3ee6-dcf1-4a06-be9c-d48da51696f5.png)

**Comment by iamtrask** [comment] 2022-11-29 16:59
> Launching a domain node using `hagrid launch --tag=latest` launched a domain node with Syft 0.6.0- could this be the cause of the issue? ![image](https://user-images.githubusercontent.com/32711264/203352984-c91846a3-4f91-421c-b260-ed7a60c61874.png)

I believe we've confirmed that this was not the issue. I was planning to reproduce on dev today but dev isn't building.

**Comment by iamtrask** [comment] 2022-11-29 17:01
> Launching a domain node using `hagrid launch --tag=latest` launched a domain node with Syft 0.6.0- could this be the cause of the issue? ![image](https://user-images.githubusercontent.com/32711264/203352984-c91846a3-4f91-421c-b260-ed7a60c61874.png)

@IshanMi I believe we've confirmed that this was not the issue. I was planning to reproduce on dev today but dev isn't building. However, running with --tag=latest still produces the same issue.

**Comment by madhavajay** [comment] 2022-12-01 05:33
> > Launching a domain node using `hagrid launch --tag=latest` launched a domain node with Syft 0.6.0- could this be the cause of the issue? ![image](https://user-images.githubusercontent.com/32711264/203352984-c91846a3-4f91-421c-b260-ed7a60c61874.png)
> 
> @IshanMi I believe we've confirmed that this was not the issue. I was planning to reproduce on dev today but dev isn't building. However, running with --tag=latest still produces the same issue.

@iamtrask  Now that `dev` is working on your machine can you see if this can be replicated?

**Comment by rasswanth-s** [comment] 2023-05-28 12:34
I am closing long standing Github Issues related to older versions of PySyft (<=0.7) and are not aligned in our current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.

**Closed by rasswanth-s** 2023-05-28 12:34 UTC
Labels: Type: Bug :bug:, Priority: 1 - Immediate :fire:, DP, Awaiting Response
