### ISSUE TITLE
Error when launching the federated-learning exemple mcfl_create_plan : host_federated_training generate "Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by Macha2021** [OpenMined/PySyft#5525] opened 2021-04-29 08:28 UTC
## Description
When I launch the exemple notebook mcfl_create_plan, I found an error when launching the process.

## How to Reproduce
1. Launch the fllowing script server.py:

![federated1](https://user-images.githubusercontent.com/83394368/116520810-7fc33f00-a8d3-11eb-8b88-96cfb98359e5.png)

2. Launch the jupyter notebook: examples/federated-learning/model-centric/mcfl_create_plan.ipynb

## Screenshots
I obtained the following error:

![response1 (3)](https://user-images.githubusercontent.com/83394368/116521452-47703080-a8d4-11eb-8803-4411b3769462.png)
![response2](https://user-images.githubusercontent.com/83394368/116521464-4c34e480-a8d4-11eb-9346-55a2cd619198.png)

The 4th part of the JSON file seems to be empty, but I cannot find why the message is divided in 4 parts.
Does someone found the same error ?

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.7
 - Browser: Edge

**Comment by LaplaceZhang** [comment] 2021-05-02 17:33
Hi, have you solved this issue? I met the same problem here, but it returns `BrokenPipeError: [Errno 32] Broken pipe`. The full screenshot is like this:

![2021-05-02 18-15-13 的屏幕截图](https://user-images.githubusercontent.com/25606364/116821598-74da0a00-ab72-11eb-8307-1bec67688ba8.png)

I googled this error online, but this error usually caused by torch.DataLoader which is not related to my issue. I think this may be caused by socket service closed, but I don't know why the PyGrid socket is disconnected. The screenshot of the terminal is like this:

![2021-05-02 18-32-17 的屏幕截图](https://user-images.githubusercontent.com/25606364/116822094-d3a08300-ab74-11eb-8b41-f0ebc07e82e9.png)


Appreciate if you know how to fix this.
 
***

And as for this error you met, this may because the `json.loads(self.ws.recv())`, you can try to add this argument `json.loads(self.ws.recv(), strict=False)` to see if your problem resolved. Hope this can help you.

**Comment by Macha2021** [comment] 2021-05-12 15:07
Since I still have issues on windows, I have tried this script on ubuntu docker container and I found the same error as your. Did you found a solution to this problem?

**Comment by LaplaceZhang** [comment] 2021-05-15 21:24
Not exactly, I still stuck here and I don't know which part went wrong. I assume it may be caused by PyGrid does not start a service properly and the stock went to sleep mode but I'm confident about this. I actually got a similar error traceback in issue [#5521](https://github.com/OpenMined/PySyft/issues/5521) but this problem is not resolved yet.

**Comment by Macha2021** [comment] 2021-05-17 14:37
Don't you think it is due to the fact that we launch the server and the client on the same computer ?

**Comment by LaplaceZhang** [comment] 2021-05-26 09:33
I think this library can be used for virtual set-up, i.e., place worker and host in one device and use socket to connect the different pipes in localhost.

**Comment by SimaZD** [comment] 2021-11-25 07:55
@LaplaceZhang i have met the same problem about

`[2021-11-25 07:43:19]: 8 DEBUG WebSocket request accepted, switching protocols`
`[2021-11-25 07:43:19]: 8 DEBUG Closed WebSocket`
`[2021-11-25 07:43:19]: 8 DEBUG Failed to write closing frame -> closing socket`
`[2021-11-25 07:43:19]: 8 DEBUG Closed WebSocket`

and then

`BrokenPipeError: [Errno 32] Broken pipe`

do you know how to fix that now ?really appreciate.

**Comment by madhavajay** [comment] 2022-11-17 07:03
0.5 is no longer supported.

**Closed by madhavajay** 2022-11-17 07:03 UTC
Labels: Type: Bug :bug:, 0.5
