### ISSUE TITLE
AssertionError: Searching for #fss_comp_plan_1 on worker1. /!\ 0 found

### ISSUE THREAD

**Issue by superxii** [OpenMined/PySyft#4473] opened 2020-08-25 06:50 UTC
Description:
AssertionError: Searching for #fss_comp_plan_1 on worker1. /!\ 0 found

## Screenshots
![Untitled](https://user-images.githubusercontent.com/63416489/91140892-57e76000-e6e2-11ea-83f9-0293be1e5a9c.png)

**Comment by teo-milea** [comment] 2020-08-25 07:57
Hello, could you provide a method to reproduce this bug? At a first glance it seems the computation command didn't find a worker, but I need a snippet to recreate the bug and help you further.

**Comment by superxii** [comment] 2020-08-25 08:29
Hi,thank you for your help.Actually, I don't know how i made this bug.Maybe I provide the code with you first and to see whether is there a bug on your side.

**Comment by teo-milea** [comment] 2020-08-25 10:57
You need to build from repo with these steps:
-  `git clone https://github.com/OpenMined/PySyft.git`
-  `cd PySyft`
-  `pip install -r pip-dep/requirements.txt` (and possibly other files from pip-dep or other dependencies to ensure the compatibility of your venv with syft)
-  `pip install -e .`  

There will be another issue to update the version from pip to the latest release.
If there is any other problem let me know!

**Comment by gmuraru** [comment] 2020-08-25 14:43
@superxii did what @teo-milea mentioned solved your problem

**Comment by superxii** [comment] 2020-08-26 01:10
It solved thanks!!! But It appeared another error with the program

Is that something i missed to install?
![Untitled](https://user-images.githubusercontent.com/63416489/91243206-ff64a100-e77b-11ea-833e-c0484b6e099c.png)

**Comment by gmuraru** [comment] 2020-09-01 06:01
Are you running on Windows?

**Comment by superxii** [comment] 2020-09-01 06:26
Yes, I was like running on Windows first before I run on Azure

**Comment by gmuraru** [comment] 2020-09-01 06:27
Could you try to run on Linux and check if the issue is still there?

**Comment by superxii** [comment] 2020-09-01 07:59
I may need some time to fix other error on Linux.

Meanwhile,in tutorial two, I followed the example code but comes out with 
![Untitled](https://user-images.githubusercontent.com/63416489/91823544-f25c1c00-ec6b-11ea-9250-85b13c85950e.png)

ImportError: cannot import name 'ReduceOp' from 'torch.distributed' (C:\Users\user\anaconda3\envs\pysyft\lib\site-packages\torch\distributed\__init__.py)

I have do some search and found that the distributed processing seems not to support windows yet,but I can ran the code in serveral weeks ago before I install with other package or libray.How can I fix this?

**Comment by gmuraru** [comment] 2020-09-01 09:34
Could you do a ```pip uninstall crypten```? CrypTen is supported only in Linux.

**Comment by superxii** [comment] 2020-09-01 09:52
Thanks, I will comeback later on for the first bugs to see whether it appears on linux or not.

**Comment by gmuraru** [comment] 2020-10-09 17:57
@superxii any update?

**Comment by cereallarceny** [comment] 2020-11-19 13:27
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.

**Closed by cereallarceny** 2020-11-19 13:27 UTC
Labels: 0.2.x, Type: Bug :bug:
