### ISSUE TITLE
Calling some data science API methods on data pointers causes `AttributeError: 'TensorWrappedPhiTensorPointer' object has no attribute 'child'`

### ISSUE THREAD

**Issue by kiendang** [OpenMined/PySyft#7043] opened 2022-11-14 05:29 UTC
## Description
Calling `ndim`, `zeros_like()`, `size` on data pointers causes `AttributeError: 'TensorWrappedPhiTensorPointer' object has no attribute 'child'`

## How to Reproduce
```py
import syft as sy
import numpy as np

domain_client = sy.login(email="info@openmined.org", password="changethis", port=8081)

arr = np.random.randint(0, 10000, (10000))

data = sy.Tensor(arr).annotate_with_dp_metadata(-1, 11000, data_subjects="Bob")
data_ptr = data.send(domain_client, tags=["my_data"])

domain_client.create_user(name="DS", email="test@email.com", password="password", budget=99999)
ds_client = sy.login(email="test@email.com", password="password", port=8081)

d_ptr = ds_client.store[data_ptr.id_at_location]
```

Calling `size()`

```py
d_ptr.size()
```

```py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [24], line 1
----> 1 d_ptr.size()

File ~/pysyft/packages/syft/src/syft/core/tensor/passthrough.py:80, in PassthroughTensor.size(self)
     77 @property
     78 def size(self) -> int:
     79     if (
---> 80         isinstance(self.child, float)
     81         or isinstance(self.child, int)
     82         or isinstance(self.child, bool)
     83     ):
     84         return 1
     86     if hasattr(self.child, "size"):

AttributeError: 'TensorWrappedPhiTensorPointer' object has no attribute 'child'
```

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by iamtrask** [comment] 2022-11-17 11:57
Before fixing this we need to decide whether we're actually going to try to modify the numpy API or whether we should just make an imitation syft.numpy module where we define our own methods (like zeroes_like()) with no connection to actual numpy. If unsure we should do the latter for now because it's easier to build and easier to change later (and less likely to be buggy)

**Comment by madhavajay** [comment] 2022-11-17 23:13
I think this is a duplicate of this:
https://github.com/OpenMined/PySyft/issues/6922

The problem is that the `Pointer` class inherits from `PassthroughTensor` I dont think thats correct because Pointers arent tensors and dont have a .child.

**Comment by kiendang** [comment] 2022-11-18 01:58
Agree. Gonna close this as duplicated

**Closed** 2022-11-18 02:01 UTC
Labels: Type: Bug :bug:, Priority: 1 - Immediate :fire:, 0.7
