### ISSUE TITLE
.list_objects_remote() allows to see private tensors

### ISSUE THREAD

**Issue by xanderwallace85** [OpenMined/PySyft#4594] opened 2020-09-24 11:17 UTC
## Description
When I use `.get()` on the private tensor I correctly receive an error. However, I can see all the private data using `.list_objects_remote()`.

## How to Reproduce
```
# send data to the node
node = DataCentricFLClient(hook, "http://127.0.0.1:5001")
private_dataset = data.private_tensor(allowed_users = ("Bob", "Alice")) 
data_pointer = private_dataset.tag('#mytag').send(node, user='Alice')
```
```
grid = sy.PublicGridNetwork(hook, "http://127.0.0.1:7000")
results = grid.search("#mytag")
res_alice = results['alice'][0]
# res_alice.get # return an error due to the permission
res_alice.location.list_objects_remote() # I can see the data in alice
```

## Expected Behavior
list_objects_remote() should throw an error if allowed user/key is not provided.

**Comment by tyoc213** [comment] 2020-09-27 04:03
I wonder if I can fix this :)... so Im new to this library and probably will need some help.

**Comment by LaRiffle** [comment] 2020-10-01 07:47
Yeah sure, give it a try @tyoc213 :)

**Comment by tyoc213** [comment] 2020-10-07 22:15
Hi  there, sorry, jusst take a look today, but with the provided code I get this...

![image](https://user-images.githubusercontent.com/506234/95393572-74b9aa80-08c0-11eb-83ca-dd6992624bc7.png)


Is this the correct setup or what Im missing to reproduce the bug @xanderwallace85 ?

Also I will be updating more  the issue with what I find, if I got stuck is this the correct place to ask for hints?

**Comment by xanderwallace85** [comment] 2020-10-08 00:20
> Hi there, sorry, jusst take a look today, but with the provided code I get this...
> 
> ![image](https://user-images.githubusercontent.com/506234/95393572-74b9aa80-08c0-11eb-83ca-dd6992624bc7.png)
> 
> Is this the correct setup or what Im missing to reproduce the bug @xanderwallace85 ?
> 
> Also I will be updating more the issue with what I find, if I got stuck is this the correct place to ask for hints?

Hi @tyoc213 , I think the error you get is due to "results['alice']". "results" seems to contain only data for "Bob". See "Out[4]".

**Comment by tyoc213** [comment] 2020-10-08 01:48
a yeah, I got that about accessing a unknow key...

I was wondering why the returned dictionary only cointains data for Bob. Im running the default `docker-compuse up` PyGrid https://github.com/OpenMined/PyGrid#1-setting-the-your-hostfile

 And was wondering why I get Bob as default for the name, indeed if I printi `node` I get `<Federated Worker id:Bob>`

so yeah, changing to `res_alice = results['Bob'][0]` works... but let me see if I can get your same example to run as spected... sorry for the random questions and blocks, figuring this out :+1:.

**Comment by xanderwallace85** [comment] 2020-10-08 03:50
> a yeah, I got that about accessing a unknow key...
> 
> I was wondering why the returned dictionary only cointains data for Bob. Im running the default `docker-compuse up` PyGrid https://github.com/OpenMined/PyGrid#1-setting-the-your-hostfile
> 
> And was wondering why I get Bob as default for the name, indeed if I printi `node` I get `<Federated Worker id:Bob>`
> 
> so yeah, changing to `res_alice = results['Bob'][0]` works... but let me see if I can get your same example to run as spected... sorry for the random questions and blocks, figuring this out 👍.

I personalised my underlying network :) Now that you have res_bob you could try to run ,get() -which should return an error- and .location.list_objetcts_remote() - which should wrongly return the data in Bob.

**Comment by tyoc213** [comment] 2020-10-09 06:27
Hi there again @xanderwallace85, I have setup this https://gist.github.com/tyoc213/a41db571f12a983812fa55ecdb93b951

In there, I call each node from 5000 to 5003 and assigned a tensor of size 1 is [1], 2 is [2,3], 3 is [4,5,6] and 4 is [7,8,9,10]. 

As you can see here 
![image](https://user-images.githubusercontent.com/506234/95549332-b172c800-09cc-11eb-82fa-468fb439e0b6.png)

each node did receive the correct "size" for each one, then printed the `list_objects_remote` which for alice is

![image](https://user-images.githubusercontent.com/506234/95549542-19c1a980-09cd-11eb-8ec3-1dbc79996f03.png)

And for dan is 
![image](https://user-images.githubusercontent.com/506234/95549566-26460200-09cd-11eb-9f0a-28e46c77a81a.png)

Which I think is correct?

Inded with that code if I do `bob[0].get()`, `dan[0].get()`, `alice[0].get()`, `charlie[0].get()` I get exception error `
GetNotPermittedError:`, but I think the list_objects_remote are listening only what is on the node?

or to reproduce error..... where should I send the different data with which user permissions? I mean even changing

![image](https://user-images.githubusercontent.com/506234/95550407-740f3a00-09ce-11eb-8322-dfc7267b96e5.png)

Seem to print same output as before

![image](https://user-images.githubusercontent.com/506234/95550440-87220a00-09ce-11eb-9423-850e27b43ab6.png)


What Im missing to reproduce the error?

**Comment by tyoc213** [comment] 2020-10-10 23:40
Hi there @LaRiffle, Im a little stuck, so I ask here:

* Should I modify the handler route on PyGrid? because I think it is an error on PyGrid (its just return the text description of the search)?.

**Because**  `.get()` is an added method over torch tensor because it is implemented in `TorchTensor(AbstractTensor)` so it check if it is a .child and raises the error... but I think the printed tensor is a string... which is the results directly from PyGrid, so I think the problem is with PyGrid not checking this and returning the __str__ of all tensors even the private ones... I dont mind checking PyGrid, at less it seems that it is handled with `@data_centric_routes.route("/search", methods=["POST"])` on https://github.com/OpenMined/PyGrid/blob/1e9512e2801c3756cf0ceeebdaceaa8395b76d1b/apps/node/src/app/main/routes/data_centric/routes.py#L253 (but dont know how do change code inside docker-up thing... wonder if you people have some hints?/tutorials)


**I have found that**

This clients connect to a PyGrid via `DataCentricFLClient(WebsocketClientWorker) and they send the request with `_send_msg_and_deserialize`.  But the search for mytag is done inside `PublicGridNetwork(AbstractGrid)#search` then for each found federated worker/client it calls its "search"... so yeah the answer already have a string containing at less the size of the private tensor (still is not a real tensor).

![image](https://user-images.githubusercontent.com/506234/95666840-65866700-0b23-11eb-87db-0a29bbb7b8c9.png)

**Comment by LaRiffle** [comment] 2020-10-14 14:24
I'll tag @IonesioJunior which might have some advice here!

**Comment by tyoc213** [comment] 2020-10-16 06:47
will love to see if this should be solved inside pygrid or pysyft... or if a fix should be applied to both sides... just wondering what is the correct way to handle this.

Also 

> list_objects_remote() should throw an error if allowed user/key is not provided.

I was wondering what this means... @xanderwallace85 could you provide an example on how to pass that "allowed user key"?

Anyway, waiting for the extra feedback to make a proposal.

**Comment by cereallarceny** [comment] 2020-11-19 13:35
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.

**Closed by cereallarceny** 2020-11-19 13:35 UTC
Labels: 0.2.x, Good first issue :mortar_board:, hacktoberfest
