### ISSUE TITLE
utils.federated_avg() gives ar error with resnet models on pysyft-0.2.9

### ISSUE THREAD

**Issue by Hjeljeli** [OpenMined/PySyft#4555] opened 2020-09-15 02:08 UTC
## Description
When I call utils.federated_avg() on resnet models, I have the following error: init() missing 2 required positional arguments: 'block' and 'layers'. Any idea how to fix this?

## System Information
Pysyft Version: 0.2.9

## Code Snippet 
import torch
from torchvision import datasets, transforms, models

import syft as sy
from syft.workers.virtual import VirtualWorker
from syft.frameworks.torch.fl import utils
hook = sy.TorchHook(torch)

alice = VirtualWorker(id="alice", hook=hook)
bob = VirtualWorker(id="bob", hook=hook)
carol = VirtualWorker(id="carol", hook=hook)
workers = [alice, bob, carol]

model_in = models.resnet50(pretrained=True)

local_models = {}
for worker in workers:
local_models[worker]= model_in.copy()

model_out = utils.federated_avg(local_models)

## Error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hamza/PySyft-0.2.9/syft/frameworks/torch/fl/utils.py", line 85, in federated_avg
    model = type(model_list[0])()
TypeError: __init__() missing 2 required positional arguments: 'block' and 'layers'

**Comment by aanurraj** [comment] 2020-09-15 15:00
Closing this issue as it is a duplicate of #4481

**Closed by aanurraj** 2020-09-15 15:00 UTC
Labels: Type: Bug :bug:
