### ISSUE TITLE
Sending private tensors throws and error when only one user is listed in "allowed_users" 

### ISSUE THREAD

**Issue by xanderwallace85** [OpenMined/PySyft#4623] opened 2020-10-01 08:15 UTC
## Description
After creating a private tensor, I get a `SendNotPermittedError` when trying to send the data to the node if only one user is listed in allowed_users.

## How to Reproduce
`private_dataset = th.tensor([1, 3.5, 47.3]).private_tensor(allowed_users = ("Alice"))
private_dataset = private_dataset.tag('#my_data')
data_pointer = private_dataset.send(site, user='Alice')`

## Expected Behavior
Possibility to define only one allowed user.

## Additional Context
To overcome this issue I am currently listing the same user twice. For instance, `allowed_users = ("Alice", "Alice")`

**Comment by gmuraru** [comment] 2020-10-01 08:35
Thank you for reporting this :+1:

**Comment by Nilanshrajput** [comment] 2020-10-01 13:23
I will take this one.

**Comment by gmuraru** [comment] 2020-10-01 13:25
:raised_hands:

**Comment by Nilanshrajput** [comment] 2020-10-01 14:16
actually this not a bug, ptivate tensor expects a list of users, `private_tensor(allowed_users = ("Alice")) ` converts to 5 users ['A', 'l' ....], 

`private_tensor(allowed_users = ("Alice",)) ` this will work
or better `private_tensor(allowed_users = ["Alice"]) `

**Comment by gmuraru** [comment] 2020-10-01 14:24
Thank you for looking into this. I think we can close it!

**Comment by Nilanshrajput** [comment] 2020-10-01 14:25
@gmuraru  should i add a method to convert string to list explicitly?

**Closed by gmuraru** 2020-10-01 14:24 UTC
Labels: Good first issue :mortar_board:, Type: Bug :bug:, hacktoberfest

**Comment by gmuraru** [comment] 2020-10-01 14:27
Nope, I think it is fine because the parameter name ```allowed_users``` allude to a list/tuple of user names

**Comment by Nilanshrajput** [comment] 2020-10-01 14:27
cool np
