### ISSUE TITLE
AttributeError: type object 'Tensor' has no attribute 'bitwise_xor_'

### ISSUE THREAD

**Issue by AbhishekPokala** [OpenMined/PySyft#4999] opened 2021-01-10 05:23 UTC
## Description
Built Syft 0.3.0 with torch 1.4 (built from this [wheel](https://github.com/sungjuGit/PyTorch-and-Vision-for-Raspberry-Pi-4B)) from branch [PySyft 0.4](https://github.com/OpenMined/PySyft/tree/0.4) but I get the AttributeError.
It looks like [torch/allowlist.py](https://github.com/OpenMined/PySyft/blob/0.4/src/syft/lib/torch/allowlist.py) doesn't contain a rule to ignore these attributes in weird-cases such as this.

## How to Reproduce
1.Build torch 1.4 from the wheel above.
2. Build Syft 0.3.0 from branch [PySyft 0.4](https://github.com/OpenMined/PySyft/tree/0.4)
3.`import syft`
4. See error.

## Expected Behavior
Syft should've been imported without throwing any errors.

## System Information
 - OS: Ubuntu armv7l 
 - Language Version: Python 3.7.5, syft 0.3.0, torch 1.4.0 (built from above wheel).

## Additional Context
#4963 
#4987

**Comment by madhavajay** [comment] 2021-01-11 00:13
As discussed this isn't a bug with Syft but we can look to work around this.

**Comment by madhavajay** [comment] 2021-01-11 00:14
The goal here would be to allow some kind of ENVIRONMENT VAR to be set before import which would allow a version of torch compiled with missing ops to still load.

**Comment by madhavajay** [comment] 2021-02-22 06:39
I will close this for now since the cause is a bad build of `torch` and not our library. If this comes back we can re-investigate.

**Closed by madhavajay** 2021-02-22 06:39 UTC
Labels: Rescope, Type: Improvement :chart_with_upwards_trend:
