### ISSUE TITLE
Plan stripped re-construction

### ISSUE THREAD

**Issue by vsquareg** [OpenMined/PySyft#5412] opened 2021-03-31 13:08 UTC
## Description
Currently, when a plan is created, it contains a lot of metadata like Pointer UIDs, VM addresses, etc. So, if the same plan is created twice, its representation would be completely different.

Solution: to re-construct the plan without any metadata.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
https://github.com/OpenMined/PySyft/issues/5359#issuecomment-807726213

**Comment by madhavajay** [comment] 2021-04-21 08:40
Duplicate of this: https://github.com/OpenMined/PySyft/issues/5292

**Closed by madhavajay** 2021-04-21 08:40 UTC
Labels: Type: Improvement :chart_with_upwards_trend:
