### ISSUE TITLE
Running the same query twice against two different data subjects still spends privacy budget somehow

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6916] opened 2022-10-28 23:34 UTC
Running the following on a fresh domain ("hagrid launch --tag=latest")

```
import syft as sy

me = sy.login(email="info@openmined.org", password="changethis", port=8081)

import numpy as np

n = 10000
_x = (np.random.randn(n) * 100)
a = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x)+":A", range(0,n))))

b = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x)+":B", range(0,n))))

me.load_dataset(assets={"a":a, "b":b}, 
                name="Test Dataset", 
                description="Short Desc")


me.create_user(name='Bob',
               email="andrew2@openmined.org",
               password="abc123",
               budget=10000000)

bob = sy.login(email="andrew2@openmined.org",
               password="abc123",
               port=8081)

initial_budget = bob.privacy_budget

x = bob.datasets[-1]['a']

out_ptr = x.mean().publish(sigma=1)
out = out_ptr.block.get()

final_budget = bob.privacy_budget

print(initial_budget, final_budget, out)


initial_budget = bob.privacy_budget

x = bob.datasets[-1]['b']

out_ptr = x.mean().publish(sigma=1)
out = out_ptr.block.get()

final_budget = bob.privacy_budget

print(initial_budget, final_budget, out)
```

Running the same query a second time against the same dataset but with a 100% disjoint set of data subjects shouldn't change the amount of privacy budget spent... although it's not clear to me whether we should reveal that to the end user. 

It's not clear to me yet what we should be revealing to the end user here. Should they know that the. dataset was on a totally disjoint set of data subjects? Should they know the degree of overlap? (even if they don't know the exact identities). Probably not.

However, we should return privacy budget information that's based on some type of assumption about data subject overlap...even if that's not grounded on the real world data.

All that is to say - there are two issues here:

1) in the backend it shouldn't spend more privacy budget on the second query
2) in the API to the data scientist we shouldn't reveal information about whether there is data subject overlap - it's not 100% clear how we do that

**Comment by IshanMi** [comment] 2022-11-16 18:28
Unable to reproduce this issue- when I ran the code posted I got the same RDP constants and epsilon spend both times
FWIW this also suffers from #6949 since sigma=1 made the RDP constant = 0.03966208 for me 

I'll circle back to this once that issue is fixed

**Comment by madhavajay** [comment] 2022-11-21 14:07
@iamtrask can you help to reproduce this?

**Comment by iamtrask** [comment] 2022-11-29 16:57
> Unable to reproduce this issue- when I ran the code posted I got the same RDP constants and epsilon spend both times FWIW this also suffers from #6949 since sigma=1 made the RDP constant = 0.03966208 for me
> 
> I'll circle back to this once that issue is fixed

@IshanMi - the measurements you describe are subtley unrelated to this issue. Both queries should create the same RDP constants and epsilon spend.

However, because they're doing so against different data subjects the amount of remaining privacy budget for the domain node (which is a max across all data subjects) should not change between the first and second query. The second query is just bringing more data subjects to the same level of epsilon spend as the first query. 

The expected behavior is for bob.privacy_budget to change after the first query is run, but for bob.privacy_budget to remain the same when the second query is run.

**Comment by madhavajay** [comment] 2022-12-05 08:29
Should be fixed by: https://github.com/OpenMined/PySyft/pull/7103

**Comment by rasswanth-s** [comment] 2023-05-28 12:33
I am closing long standing Github Issues related to older versions of PySyft (<=0.7) and are not aligned in our current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.

**Closed by rasswanth-s** 2023-05-28 12:33 UTC
Labels: Type: Bug :bug:, Priority: 1 - Immediate :fire:, DP, Syft
