### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by niklausliu** [OpenMined/PySyft#2607] opened 2019-09-10 14:37 UTC
**Describe the bug**
TypeError: object of type 'NoneType' has no len()

**My code**
```python
x_train = torch.tensor(train_x)
y_train = torch.tensor(train_y)

import syft as sy
# Hook that extends the Pytorch library to enable all computations with pointers of tensors sent to other workers
hook = sy.TorchHook(torch)

# Creating 2 virtual workers
bob = sy.VirtualWorker(hook, id="bob")
anne = sy.VirtualWorker(hook, id="anne")
#datasets=[]
# threshold indexes for dataset split (one half for Bob, other half for Anne)
train_idx = int(len(x_train)/2)


# Sending toy datasets to virtual workers
#data_bob = x_train[:train_idx].send(bob)
#data_anne = x_train[train_idx:].send(anne)
#target_bob = y_train[:train_idx].send(bob)
#target_anne = y_train[train_idx:].send(anne)

#bob_train_dataset = sy.BaseDataset(data_bob , target_bob).send(bob)
#anne_train_dataset = sy.BaseDataset(data_anne, target_anne).send(anne)

#datasets = [(data_bob,target_bob),(data_anne,target_anne)]
#federated_train_dataset = sy.FederatedDataset([(data_bob,target_bob), (data_anne, target_anne)])
#bob_train_dataset = sy.BaseDataset(data_bob, target_bob).send(bob)
#anne_train_dataset = sy.BaseDataset(data_anne, target_anne).send(anne)
# Creating federated datasets, an extension of Pytorch TensorDataset class
#federated_train_dataset = sy.FederatedDataset([bob_train_dataset, anne_train_dataset])


# Creating federated dataloaders, an extension of Pytorch DataLoader class
#federated_train_loader = sy.FederatedDataLoader(federated_train_dataset, shuffle=True, batch_size=64)


# Hook that extends the Pytorch library to enable all computations with pointers of tensors sent to other workers
#hook = sy.TorchHook(torch)

# Creating 2 virtual workers
#bob = sy.VirtualWorker(hook, id="bob")
#anne = sy.VirtualWorker(hook, id="anne")

# threshold indexes for dataset split (one half for Bob, other half for Anne)
#train_idx = int(len(train_labels)/2)

# Sending toy datasets to virtual workers
bob_train_dataset = sy.BaseDataset(x_train[:train_idx], y_train[:train_idx]).send(bob)
anne_train_dataset = sy.BaseDataset(x_train[train_idx:], y_train[train_idx:]).send(anne)

# Creating federated datasets, an extension of Pytorch TensorDataset class
federated_train_dataset = sy.FederatedDataset([bob_train_dataset, anne_train_dataset])
# Creating federated dataloaders, an extension of Pytorch DataLoader class
federated_train_loader = sy.FederatedDataLoader(federated_train_dataset, shuffle=True, batch_size=64)

class GRUNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, n_layers, drop_prob=0.2):
        super(GRUNet, self).__init__()
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        
        self.gru = nn.GRU(input_dim, hidden_dim, n_layers, batch_first=True, dropout=drop_prob)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()
        
    def forward(self, x, h):
        out, h = self.gru(x, h)
        out = self.fc(self.relu(out[:,-1]))
        return out, h
    
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device)
        return hidden

class LSTMNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, n_layers, drop_prob=0.2):
        super(LSTMNet, self).__init__()
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        
        self.lstm = nn.LSTM(input_dim, hidden_dim, n_layers, batch_first=True, dropout=drop_prob)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()
        
    def forward(self, x, h):
        out, h = self.lstm(x, h)
        out = self.fc(self.relu(out[:,-1]))
        return out, h
    
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device))
        return hidden

batch_size = 64
def train(federated_train_loader, learn_rate, hidden_dim=256, EPOCHS=5, model_type="GRU"):
    
    # Setting common hyperparameters
    input_dim = next(iter(federated_train_loader))[0].shape[2]
    output_dim = 1
    n_layers = 2
    # Instantiating the models
    if model_type == "GRU":
        model = GRUNet(input_dim, hidden_dim, output_dim, n_layers)
    else:
        model = LSTMNet(input_dim, hidden_dim, output_dim, n_layers)
    model.to(device)
    
    # Defining loss function and optimizer
    criterion = nn.MSELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=learn_rate)
    
    model.train()
    print("Starting Training of {} model".format(model_type))
    epoch_times = []
    # Start training loop
    for epoch in range(1,EPOCHS+1):
        start_time = time.clock()
        h = model.init_hidden(batch_size)
        avg_loss = 0.
        counter = 0
        for x, label in federated_train_loader:
            worker = x.location
            #h = torch.Tensor(np.zeros((batch_size))).send(worker)
            model.send(worker)
            counter += 1
            if model_type == "GRU":
                h = h.data
            else:
                h = tuple([e.data for e in h])
            model.zero_grad()
           
            
            out, h = model(x.to(device).float(), h)
            loss = criterion(out, label.to(device).float())
            loss.backward()
            optimizer.step()
            avg_loss += loss.item()
            if counter%200 == 0:
                print("Epoch {}......Step: {}/{}....... Average Loss for Epoch: {}".format(epoch, counter, len(train_loader), avg_loss/counter))
        current_time = time.clock()
        print("Epoch {}/{} Done, Total Loss: {}".format(epoch, EPOCHS, avg_loss/len(train_loader)))
        print("Time Elapsed for Epoch: {} seconds".format(str(current_time-start_time)))
        epoch_times.append(current_time-start_time)
    print("Total Training Time: {} seconds".format(str(sum(epoch_times))))
    return model
```
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version : 16.04

**Additional context**
Starting Training of GRU model

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-6d641218ab70> in <module>()
      1 lr = 0.001
      2 #batch_size = 64
----> 3 gru_model = train(federated_train_loader, lr, model_type="GRU")

<ipython-input-36-ba6a40ede7c3> in train(federated_train_loader, learn_rate, hidden_dim, EPOCHS, model_type)
     38 
     39 
---> 40             out, h = model(x.to(device).float(), h)
     41             loss = criterion(out, label.to(device).float())
     42             loss.backward()

Actually, I do not know what happen on my dataset?

**Comment by niklausliu** [comment] 2019-09-10 14:38
Why my data is Nonetype?

**Comment by DanyEle** [comment] 2019-09-11 07:02
When using `model.to(device)` you are trying to move your data structure to a GPU, right? Well, as far as I know, this operation is not supported in PySyft yet. Keep the computation on the CPU for now.

**Comment by niklausliu** [comment] 2019-09-11 07:42
> When using `model.to(device)` you are trying to move your data structure to a GPU, right? Well, as far as I know, this operation is not supported in PySyft yet. Keep the computation on the CPU for now.

Thanks for your reply. I solved my previous problem because the version of PySyft was too old. Now there is a new bug.
RuntimeError                              Traceback (most recent call last)
<ipython-input-62-6d641218ab70> in <module>()
      1 lr = 0.001
      2 #batch_size = 64
----> 3 gru_model = train(federated_train_loader, lr, model_type="GRU")

<ipython-input-61-0ac6d91a093c> in train(federated_train_loader, learn_rate, hidden_dim, EPOCHS, model_type)
     48             print(x.shape)
     49             print(label.shape)
---> 50             out, h = model(x, h)
     51             loss = criterion(out, label.float())
     52             loss.backward()

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

<ipython-input-54-a172098b1c99> in forward(self, x, h)
     10 
     11     def forward(self, x, h):
---> 12         out, h = self.gru(x, h)
     13         out = self.fc(self.relu(out[:,-1]))
     14         return out, h

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
    205             hx = self.permute_hidden(hx, sorted_indices)
    206 
--> 207         self.check_forward_args(input, hx, batch_sizes)
    208         _impl = _rnn_impls[self.mode]
    209         if batch_sizes is None:

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/rnn.py in check_forward_args(self, input, hidden, batch_sizes)
    173 
    174     def check_forward_args(self, input, hidden, batch_sizes):
--> 175         self.check_input(input, batch_sizes)
    176         expected_hidden_size = self.get_expected_hidden_size(input, batch_sizes)
    177 

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/rnn.py in check_input(self, input, batch_sizes)
    151             raise RuntimeError(
    152                 'input.size(-1) must be equal to input_size. Expected {}, got {}'.format(
--> 153                     self.input_size, input.size(-1)))
    154 
    155     @weak_script_method

RuntimeError: input.size(-1) must be equal to input_size. Expected 5, got 0

**Comment by DanyEle** [comment] 2019-09-11 08:15
Can you please show me how the `device` variable is defined?

Also, you may want to try your code without the `.to(device)` call in your code.

**Comment by niklausliu** [comment] 2019-09-11 08:31
> Can you please show me how the `device` variable is defined?
> 
> Also, you may want to try your code without the `.to(device)` call in your code.

# torch.cuda.is_available() checks and returns a Boolean True if a GPU is available, else it'll return False
is_cuda = torch.cuda.is_available()

# If we have a GPU available, we'll set our device to GPU. We'll use this device variable later in our code.
if is_cuda:
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

**Comment by DanyEle** [comment] 2019-09-11 08:33
Yes, that's exactly what I meant. PySyft does not support CUDA GPUs yet, though we'd like to support this functionality @robert-wagner 

What is the result of running your code when removing all statements `.to(device)` @niklausliu ?

**Comment by niklausliu** [comment] 2019-09-11 08:36
> Yes, that's exactly what I meant. PySyft does not support CUDA GPUs yet, though we'd like to support this functionality in the future @robert-wagner
> 
> What is the result of running your code when removing all statements `.to(device)` @niklausliu ?

Thanks for your reply. But I have a new bug about rnn.py, you can see more detail as follow:

RuntimeError Traceback (most recent call last)
in ()
1 lr = 0.001
2 #batch_size = 64
----> 3 gru_model = train(federated_train_loader, lr, model_type="GRU")

in train(federated_train_loader, learn_rate, hidden_dim, EPOCHS, model_type)
48 print(x.shape)
49 print(label.shape)
---> 50 out, h = model(x, h)
51 loss = criterion(out, label.float())
52 loss.backward()

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/module.py in call(self, *input, **kwargs)
491 result = self._slow_forward(*input, **kwargs)
492 else:
--> 493 result = self.forward(*input, **kwargs)
494 for hook in self._forward_hooks.values():
495 hook_result = hook(self, input, result)

in forward(self, x, h)
10
11 def forward(self, x, h):
---> 12 out, h = self.gru(x, h)
13 out = self.fc(self.relu(out[:,-1]))
14 return out, h

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/module.py in call(self, *input, **kwargs)
491 result = self._slow_forward(*input, **kwargs)
492 else:
--> 493 result = self.forward(*input, **kwargs)
494 for hook in self._forward_hooks.values():
495 hook_result = hook(self, input, result)

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
205 hx = self.permute_hidden(hx, sorted_indices)
206
--> 207 self.check_forward_args(input, hx, batch_sizes)
208 _impl = _rnn_impls[self.mode]
209 if batch_sizes is None:

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/rnn.py in check_forward_args(self, input, hidden, batch_sizes)
173
174 def check_forward_args(self, input, hidden, batch_sizes):
--> 175 self.check_input(input, batch_sizes)
176 expected_hidden_size = self.get_expected_hidden_size(input, batch_sizes)
177

~/anaconda3/envs/pysyft/lib/python3.6/site-packages/torch/nn/modules/rnn.py in check_input(self, input, batch_sizes)
151 raise RuntimeError(
152 'input.size(-1) must be equal to input_size. Expected {}, got {}'.format(
--> 153 self.input_size, input.size(-1)))
154
155 @weak_script_method

RuntimeError: input.size(-1) must be equal to input_size. Expected 5, got 0

**Comment by DanyEle** [comment] 2019-09-11 08:43
Well, I believe the issue is related to the suggestion I gave you, with the `.to(device)` statement, because I encountered similar errors when running it on a CPU/GPU using the `device`.

Alternatively, @andrelmfarias  could have some other ideas?

Is what you posted the output of the code with the `.to(device)` statement removed at all places in your code?

**Comment by niklausliu** [comment] 2019-09-11 08:56
> Well, I believe the issue is related to the suggestion I gave you, with the `.to(device)` statement, because I encountered similar errors when running it on a CPU/GPU using the `device`.
> 
> Alternatively, @andrelmfarias could have some other ideas?
> 
> Is what you posted the output of the code with the `.to(device)` statement removed at all places in your code?

But I found that I deleted all the statements about the device or the bug I described above.

**Comment by niklausliu** [comment] 2019-09-11 09:23
> Well, I believe the issue is related to the suggestion I gave you, with the `.to(device)` statement, because I encountered similar errors when running it on a CPU/GPU using the `device`.
> 
> Alternatively, @andrelmfarias could have some other ideas?
> 
> Is what you posted the output of the code with the `.to(device)` statement removed at all places in your code?

**Comment by niklausliu** [comment] 2019-09-11 09:25
> > Well, I believe the issue is related to the suggestion I gave you, with the `.to(device)` statement, because I encountered similar errors when running it on a CPU/GPU using the `device`.
> > Alternatively, @andrelmfarias could have some other ideas?
> > Is what you posted the output of the code with the `.to(device)` statement removed at all places in your code?
> 
> But I found that I deleted all the statements about the device or the bug I described above.

Sorry, I mean, I deleted all the statements about the device, but it did not work and the bug still exists.

**Comment by andrelmfarias** [comment] 2019-09-11 09:37
Can you please print the output you get from your dataset before and after hooking torch?

**Comment by niklausliu** [comment] 2019-09-11 10:19
> Can you please print the output you get from your dataset before and after hooking torch?
![image](https://user-images.githubusercontent.com/31737021/64689120-4781a980-d4c0-11e9-95d4-6ea294a36e95.png)

![image](https://user-images.githubusercontent.com/31737021/64689149-5cf6d380-d4c0-11e9-94f4-75359fe1e289.png)

![image](https://user-images.githubusercontent.com/31737021/64689251-929bbc80-d4c0-11e9-9a5b-737aba54f4d9.png)

![image](https://user-images.githubusercontent.com/31737021/64689279-9cbdbb00-d4c0-11e9-9966-108178b67676.png)

**Comment by niklausliu** [comment] 2019-09-11 10:20
> Can you please print the output you get from your dataset before and after hooking torch?

![image](https://user-images.githubusercontent.com/31737021/64689389-db537580-d4c0-11e9-8718-1e374d581df4.png)

**Comment by andrelmfarias** [comment] 2019-09-11 10:27
@niklausliu I found out what your errors is: you are using pytorch native GRUs and hooking torch. We do not support hooking pytorch's native RNNs at the moment, you should import the GRU module from `syft.frameworks.torch.nn`.

Please be aware syft RNNs modules work for federated learning and MPC prediction only (MPC training is not currently supported)

**Comment by niklausliu** [comment] 2019-09-11 10:39
> @niklausliu I found out what your error is: you are using pytorch native GRUs and hooking torch. We do not support hooking pytorch's native RNNs at the moment, you should import the GRU module from `syft.frameworks.torch.nn`.
> 
> Please be aware syft RNNs modules work for federated learning and MPC prediction only (MPC training is not currently supported)

Thanks for your help. I am going to modify my code. Can you leave me your email address? I think maybe I still have a lot of bugs, because this is my first time using pysyft.

**Comment by niklausliu** [comment] 2019-09-11 14:35
> @niklausliu I found out what your error is: you are using pytorch native GRUs and hooking torch. We do not support hooking pytorch's native RNNs at the moment, you should import the GRU module from `syft.frameworks.torch.nn`.
> 
> Please be aware syft RNNs modules work for federated learning and MPC prediction only (MPC training is not currently supported)

But I have seen many examples of syft GRUs module and have not found any difference with my pytorch native GRUs. Can you give me a few examples of the syft GRUs module?

**Comment by niklausliu** [comment] 2019-09-11 14:38
> @niklausliu I found out what your error is: you are using pytorch native GRUs and hooking torch. We do not support hooking pytorch's native RNNs at the moment, you should import the GRU module from `syft.frameworks.torch.nn`.
> 
> Please be aware syft RNNs modules work for federated learning and MPC prediction only (MPC training is not currently supported)

And I can not find syft.framworks.torch.nn in this website https://pysyft.readthedocs.io/en/latest/modules/syft.core.frameworks.html

**Comment by andrelmfarias** [comment] 2019-09-11 14:42
They were recently added to pysyft, so they are not included in the main documentation yet.

You can take a look at the modules here:
https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/nn/rnn.py

But in fact, they work exactly as PyTorch API (same args, etc.) you just need to import them from `syft.frameworks.torch.nn` (eg: `from syft.frameworks.torch.nn import GRU, LSTM, RNN` ) and manage them the same way you would manage a pytorch GRU

**Comment by niklausliu** [comment] 2019-09-11 14:48
> They were recently added to pysyft, so they are not included in the main documentation yet.
> 
> You can take a look at the modules here:
> https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/nn/rnn.py
> 
> But in fact, they work exactly as PyTorch API (same args, etc.) you just need to import them from `syft.frameworks.torch.nn` (eg: `from syft.frameworks.torch.nn import GRU, LSTM, RNN` ) and manage them the same way you would manage a pytorch GRU

Thanks for your help. I will adjust my code again and I will tell you any updates. Thank you again for your help.

**Comment by cereallarceny** [comment] 2019-09-11 14:53
> Thanks for your help. I am going to modify my code. Can you leave me your email address? I think maybe I still have a lot of bugs, because this is my first time using pysyft.

@niklausliu - **We're happy to help in the OpenMined community.**  But as a general rule, we're not tech support.  While you may have a problem running PySyft, and there may be a legitimate issue here, **everyone** who works on the OpenMined project works for free.  I just want to set a clear expectation that we aren't here to be your personal tech support and we certainly aren't here to provide our personal email addresses so that you can ping us with constant questions.

I'm going to close this issue for now as it seems that problem you're now having is totally unrelated to the original issue.  If that's not the case, please send me a message on Slack and I'll be happy to re-open the issue.

**Closed by cereallarceny** 2019-09-11 14:53 UTC

**Comment by niklausliu** [comment] 2019-09-11 15:30
> Not a problem @niklausliu! We're happy to have people passionate about the project like yourself. It seems this particular issue has gotten off-topic. I'd suggest you post your questions in the #team_pysyft channel on Slack and give 1-2 days for someone to reply. If not, submit a new issue here.

OK, I got it! Thank you for your help!!!
