### ISSUE TITLE
hagrid does not "land" correctly

### ISSUE THREAD

**Issue by petermchale** [OpenMined/PySyft#8760] opened 2024-04-25 16:18 UTC
## Description
hagrid does not "land" correctly. 

## How to Reproduce
1. hagrid launch test
2. hagrid land test
3. `error while interpolating services.proxy.networks.[]: required variable TRAEFIK_PUBLIC_NETWORK is missing a value: Variable not set`
4. I deleted the containers from the Docker dashboard, and then deleted the corresponding images and volumes 

## Expected Behavior
hagrid should land without error, and there should be no containers, images or volumes visible in the Docker dashboard after issuing `hagrid land test`

## Screenshots
<img width="1125" alt="Screenshot 2024-04-26 at 9 34 04 PM" src="https://github.com/OpenMined/PySyft/assets/19557137/36f5eea2-cfc3-48cd-8179-549f0550e1e3">
<img width="930" alt="Screenshot 2024-04-26 at 9 36 34 PM" src="https://github.com/OpenMined/PySyft/assets/19557137/7faa1e7f-c1b5-47f0-8cd6-cfaf10a2eff2">
<img width="1472" alt="Screenshot 2024-04-26 at 9 40 24 PM" src="https://github.com/OpenMined/PySyft/assets/19557137/b7b16968-cfeb-4e5e-b950-7175f7177e0d">

## System Information
- OS: macOS silicon
- OS Version: 14.4.1 (Sonoma)
- Language Version: Python 3.12.2
- Package Manager Version: conda 22.9.0, pip 23.3.1
- Browser (if applicable): n/a
- Browser Version (if applicable): n/a

## Additional Context
Docker Desktop Version 4.29.0 (145265)

**Comment by petermchale** [comment] 2024-04-25 17:30
I also get this error when re-executing `hagrid land test`: 

```
error while interpolating services.frontend.image: required variable DOCKER_IMAGE_FRONTEND is missing a value: Variable not set
```

**Comment by petermchale** [comment] 2024-04-26 21:48
Any idea what I might be doing wrong here @madhavajay ?

**Comment by madhavajay** [comment] 2024-05-09 23:36
@petermchale im unsure what the issue is, you can also remove the containers using `docker rm $(docker ps -aq) --force`.

But warning that will kill all your containers so if you are running something other than syft it will also be removed.

**Comment by petermchale** [comment] 2024-05-10 02:40
Thanks. I was able to remove the containers from the Docker Desktop dashboard.

**Comment by rj3d** [comment] 2024-05-14 22:12
I'm also running into this issue. I've gotten a few different error messages, but this is the most common one.
`error while interpolating services.seaweedfs.image: required variable DOCKER_IMAGE_SEAWEEDFS is missing a value: Variable not set`

**Comment by madhavajay** [comment] 2024-05-15 06:44
@rj3d we're you able to remove the containers manually? We are currently changing the way that syft is deployed so this problem will go away in a future release.

**Comment by madhavajay** [comment] 2024-05-30 02:43
We have deprecated `hagrid` so I will close this issue for now.

**Closed as completed by madhavajay** 2024-05-30 02:43 UTC
Labels: Type: Bug :bug:
