### ISSUE TITLE
Small rounding errors in handcrafted Conv2d and Pool2d Layers

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2927] opened 2020-01-18 16:00 UTC
**Describe the bug**
There is a small rounding error in these layers, as discussed in https://github.com/OpenMined/PySyft/pull/2896/files/fa21f480c8bfe4196dac2f911cd938db7ff96f03#diff-369e971f29cf5226c9b64f75072095ac

**To Reproduce**
Run the following unit tests

https://github.com/OpenMined/PySyft/blob/39d2be0aeb4b5aa0413b6b8696cccb7fb960ab0d/test/torch/nn/test_conv.py#L7

https://github.com/OpenMined/PySyft/blob/39d2be0aeb4b5aa0413b6b8696cccb7fb960ab0d/test/torch/nn/test_pool.py#L6

**Expected behavior**
Ideally there would be 0 rounding error, but this might be a PyTorch issue not us.

**Comment by arshjot** [comment] 2020-01-21 10:17
I investigated this a bit and found that we need to do a direct summation instead of calculating sum of sums. The following modifications are required:
* [`conv.py`](https://github.com/OpenMined/PySyft/blob/acdc96828cebae674817d238f68e0e81dfd41071/syft/frameworks/torch/nn/conv.py#L94-L95) - change `.sum(3).sum(3)` to `.sum((3, 4))`
* [`pool.py`](https://github.com/OpenMined/PySyft/blob/acdc96828cebae674817d238f68e0e81dfd41071/syft/frameworks/torch/nn/pool.py#L65) - change `.sum(2).sum(2)` to `.sum((2, 3))`

By making the above changes, we get exactly the same output for both the pooling implementations. However, a rounding error is still present for convolution possibly due to floating-point arithmetic as indicated [here](https://discuss.pytorch.org/t/pytorch-conv2d-vs-numpy-reference-different-outcomes-rounding-error-or-mistake/8921).

**Comment by karlhigley** [comment] 2020-01-21 17:21
@arshjot Thanks for looking into it! Could you submit a PR with those changes?

**Comment by arshjot** [comment] 2020-01-21 19:20
Yes, I'll be happy to do so!

**Comment by iamtrask** [comment] 2020-01-21 22:25
Incredible work!

**Comment by iamtrask** [comment] 2020-01-24 10:13
As reported - there is still rounding error in the Conv2d implementation. This issue should stay open until it is resolved. I have spent a few more hours looking into it and haven't found anything yet.

**Comment by LaRiffle** [comment] 2020-01-24 10:28
That's strange, it looks like the PR solved it and chnaged the test form approx to exact check didn't it?

**Comment by arshjot** [comment] 2020-01-24 10:39
The issue is solved for the pooling implementation but not for Conv2d. The Conv2d implementation also had the same discrepancy but even after rectifying it we do not get an exact match. I guess I should have specified that the PR solves *part* of this issue.

**Comment by gmuraru** [comment] 2020-01-27 22:00
This issue was fixed by #2964 (for the conv2d layer) and #2945 (for the pooling layer)

**Closed by gmuraru** 2020-01-27 22:00 UTC
Labels: bug, pytorch
